
version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    volumes:
      - ./sql/initdb.d:/docker-entrypoint-initdb.d
      - ./sql/data:/var/lib/mysql
    ports:
      - "3306:3306"
